version: "3.8"

services:
  xray-trojan:
    image: ghcr.io/xtls/xray-core:latest
    container_name: xray-trojan
    restart: always
    volumes:
      - ./config.json:/etc/xray/config.json
    command: run -c /etc/xray/config.json
    networks:
      - tunnel-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token eyJhIjoiNWQ3NWFkOTFiYzYyMTA4NmExOTA4OTczNTkwMDUxYzMiLCJ0IjoiNmIyYTE0MzMtYjhmMS00YWE2LTg2ZWQtMGI0ZGY0MDEzZWYzIiwicyI6IlpHVTNaV00wWVRVdFpEWmhZaTAwT0RGbUxXRTNNV0V0TWpKaE4ySTFNV0psTXprNCJ9
    networks:
      - tunnel-net
    depends_on:
      - xray-trojan

networks:
  tunnel-net:
    driver: bridge
