version: "3.8"

services:
  xray-trojan:
    image: ghcr.io/xtls/xray-core:latest
    container_name: xray-trojan
    restart: always
    volumes:
      - ./config.json:/etc/xray/config.json
    command: run -c /etc/xray/config.json
    networks:
      - tunnel-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token eyJhIjoiNTVmM2E5ODI3NzI4MGMzMTNkZWQ1NTI0NjQ4ODU1MTIiLCJ0IjoiMDkxMTYxNmUtMzc1OS00ODkxLWJiYmEtNDdjZGJkODAxMzIxIiwicyI6Ik9XUTFNakJtTldFdE5EUmpOeTAwTURrM0xUZ3hObVF0T1dObE9HVTNPR1F5T0dWaCJ9
    networks:
      - tunnel-net
    depends_on:
      - xray-trojan

networks:
  tunnel-net:
    driver: bridge
